Spring:
  datasource:
    password: fabrica2024*
    url: jdbc:postgresql://localhost:5432/Crud
    username: fabrica
  jpa:
    database: POSTGRESQL
    generate-ddl: True
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres